### ISSUE TITLE
Put the addons in ascending or descending order of size

### ISSUE THREAD

**Issue by mteomi** [FlorianLeChat/Steam-Collection-Download-Size-Calculator#1]
Would you introduce a function to put the addons in ascending or descending order of size?

**Comment by FlorianLeChat** [comment]
Thanks for your suggestion, I've added it to the latest builds available [here](https://github.com/FlorianLeChat/Steam-Collection-Download-Size-Calculator/actions/runs/5386792280). If you have any other feedback, you're welcome to create a new issue 👍
