### ISSUE TITLE
Sorting order bug: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by M-Davies** [FlorianLeChat/Steam-Collection-Download-Size-Calculator#4]
**Describe the bug**
The program errors out when I provide a sorting order for a workshop collection. If I do not provide a sorting order, it works fine.

**To Reproduce**
See Screenshots

**Expected behavior**
The mods to be sorted and no error generated. This is what happens when I don't provide a sorting order.

**Screenshots**
```
PS D:\Tools\Installs\Steam-Collection-Download-Size-Calculator-windows-builds-dotnet-8.x\win-x64\publish> .\SteamCollectionDownloadSizeCalculator.exe
-----------------------------------------
Steam Collection Download Size Calculator
-----------------------------------------

Please provide a Workshop object identifier (you can also put several in a row by putting ";" between each).
Example: "https://steamcommunity.com/sharedfiles/filedetails/?id=1448345830" or "1448345830;947461782".

=> https://steamcommunity.com/workshop/filedetails/?id=2654746291

Do you want to order objects by size?
Type "ASC" for ascending sorting, "DESC" for descending sorting, or leave blank if you don't want any sorting.

=> DESC

Descending sorting (heaviest files first).

Do you want to save console output to a text file? [y/N] y
Console output will be saved in a "output.log" file in application directory.

Steam API says that the object is a Workshop collection containing 86 items.
Starting computation...

The given key was not present in the dictionary.
Do you need to calculate another collection? [Y/n]
```

**Additional context**
- Both ASC and DESC are subject to this
- Running on Windows 10

**Comment by FlorianLeChat** [comment]
Thanks for your report, it's fixed on my side. Can you also confirm with the latest builds?

<ins>All builds</ins>: https://github.com/FlorianLeChat/Steam-Collection-Download-Size-Calculator/actions/runs/8580202057
<ins>Windows build with .NET 8</ins>: https://github.com/FlorianLeChat/Steam-Collection-Download-Size-Calculator/actions/runs/8580202057/artifacts/1390595865

**Comment by M-Davies** [comment]
Yep fixed for me, cheers
