### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by Yasaiek** [FlorianLeChat/Steam-Collection-Download-Size-Calculator#5]
Hello i have Issiue with using 
![image](https://github.com/FlorianLeChat/Steam-Collection-Download-Size-Calculator/assets/128112068/8dfcf1a3-0567-4839-8522-c58f017ca929)

**Comment by FlorianLeChat** [comment]
Thanks for your feedback, this issue had been resolved previously (#4) but I hadn't pushed the changes into a new version. All the latest fixes have been published here: https://github.com/FlorianLeChat/Steam-Collection-Download-Size-Calculator/releases/tag/v1.1.5 👍

**Comment by Yasaiek** [comment]
Thanks
